# Maintainer: Rust CLI WG
#
# This PKGBUILD was generated by `cargo aur`: https://crates.io/crates/cargo-aur

pkgname=grrs-bin
pkgver=0.1.0
pkgrel=1
pkgdesc="An alternative to `grep` but worse"
url="https://github.com/rust-cli/book/tree/master/src/tutorial"
license=("MIT OR Apache-2.0")
arch=("x86_64")
provides=("grrs")
conflicts=("grrs")
source=("https://github.com/thuyencode/learn-rust-cli/releases/download/v$pkgver/grrs-$pkgver-x86_64.tar.gz")
sha256sums=("541a32b1e1a946ef61e8292b06c5859c9af8b5d1f7c562c783e1084bab8ac0d5")

package() {
    install -Dm755 grrs -t "$pkgdir/usr/bin"
    install -Dm644 LICENSE.txt "$pkgdir/usr/share/licenses/$pkgname/LICENSE.txt"
}
